spring.application.name=inventorymanagement
server.port=9090
spring.jackson.serialization.write-dates-as-timestamps=false

spring.data.mongodb.uri=mongodb+srv://jessicaortiz:mUdoeYJr2WQ65Xwg@cluster0.n6pyfml.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=inventoryDB